version: '3'

services:
  db:
    image: mariadb:latest
    container_name: db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: RaceAPI
      MYSQL_USER: race
      MYSQL_PASSWORD: race
    volumes:
      - ./database:/var/lib/mysql